#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"
 
mod 'puppetlabs-stdlib'

mod 'puppetlabs-ntp',
     :git => 'https://github.com/puppetlabs/puppetlabs-ntp.git'
mod 'puppetlabs-apt',
     :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
     :ref => '1.4.x'
mod 'testenv',
     :git => 'https://github.com/GMKBabu/testenv.git',
     :branch => 'master'

mod 'puppetlabs-apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'
